name: Test

on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"

jobs:
  test-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            9.0.x
      - run: dotnet build -c Debug
      - run: dotnet test -c Debug --no-build
     
  test-unity:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unityVersion:
        - 2022.2.21f1
        include:
        - unityVersion: 2022.2.21f1
          license: UNITY_LICENSE_2022_2
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: src/ViralRouter.Unity/Library
        key: Library-VitalRouter #-${{ matrix.unityVersion }}-${{ matrix.feature }}
        restore-keys: |
          Library-ViralRouter-
          Library-
    - uses: game-ci/unity-test-runner@v4
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_LICENSE: ${{ secrets[matrix.license] }}
      with:
        projectPath: ./src/VitalRouter.Unity
        githubToken: ${{ secrets.GITHUB_TOKEN }}
      
  # test-libmruby-linux:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       submodules: recursive
  #   - working-directory: ${{ github.workspace }}/tests/vitalrouter-mruby-tests
  #     run: MRUBY_LIBPATH=${{ github.workspace }}/src/VitalRouter.Unity/Assets/VitalRouter.MRuby/Runtime/Plugins/linux-x64/VitalRouter.MRuby.Native.so make
    
  # test-libmruby-macOS:
  #   runs-on: macos-latest
  #   timeout-minutes: 10
  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       submodules: recursive
  #   - working-directory: ${{ github.workspace }}/tests/vitalrouter-mruby-tests
  #     run: MRUBY_LIBPATH=${{ github.workspace }}/src/VitalRouter.Unity/Assets/VitalRouter.MRuby/Runtime/Plugins/macOS-arm64/VitalRouter.MRuby.Native.dylib make
    
  # test-libmruby-windows:
  #   runs-on: windows-latest
  #   timeout-minutes: 10
  #   steps:
  #     - uses: actions/checkout@v3
  #     - working-directory: ${{ github.workspace }}/tests/vitalrouter-mruby-tests
  #       run: MRUBY_LIBRARY=${{ github.workspace }}/src/VitalRouter.Unity/Assets/VitalRouter.MRuby/Runtime/Plugins/windows-x64/VitalRouter.MRuby.Native.dylib make
    
